version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Paris
    target-branch: main
    commit-message:
      prefix: deps/gha
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Paris
    target-branch: main
    commit-message:
      prefix: deps/pip
    groups:
      python:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Paris
    target-branch: main
    commit-message:
      prefix: deps/docker
    groups:
      docker:
        patterns: ["*"]
