"""Cache management handlers."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel

from ..schemas.cache import CacheFileKey, CacheFilesDeleteRequest

if TYPE_CHECKING:
    from .params import (
        BunkerWebClientProtocol,
        CacheDeleteBulkParams,
        CacheFetchParams,
        CacheFileKeyParams,
        CacheListParams,
    )


def _serialize_response(response: BaseModel) -> dict[str, Any]:
    """Serialize a Pydantic response model to dict."""
    return response.model_dump(mode="json", exclude_none=True)


def _build_cache_key(params: CacheFileKeyParams) -> CacheFileKey:
    """Build a CacheFileKey from params."""
    return CacheFileKey(
        service=params.service,
        plugin=params.plugin,
        jobName=params.job_name,
        fileName=params.file_name,
    )


async def handle_list_cache(
    client: BunkerWebClientProtocol, params: CacheListParams
) -> dict[str, Any]:
    """List cache files generated by jobs."""
    response = await client.list_cache(
        service=params.service,
        plugin=params.plugin,
        job_name=params.job_name,
        with_data=params.with_data,
    )
    return _serialize_response(response)


async def handle_delete_cache_bulk(
    client: BunkerWebClientProtocol, params: CacheDeleteBulkParams
) -> dict[str, Any]:
    """Delete multiple cache files."""
    keys = [_build_cache_key(item) for item in params.files]
    request = CacheFilesDeleteRequest(cache_files=keys)
    response = await client.delete_cache_files(request)
    return _serialize_response(response)


async def handle_fetch_cache_file(
    client: BunkerWebClientProtocol, params: CacheFetchParams
) -> dict[str, Any]:
    """Fetch a cache file (base64-encoded when binary)."""
    result = await client.fetch_cache_file(
        service=params.service or "global",
        plugin_id=params.plugin,
        job_name=params.job_name,
        file_name=params.file_name,
        download=params.download,
    )
    return result


async def handle_delete_cache_file(
    client: BunkerWebClientProtocol, params: CacheFileKeyParams
) -> dict[str, Any]:
    """Delete a single cache file."""
    response = await client.delete_cache_file(
        service=params.service or "global",
        plugin_id=params.plugin,
        job_name=params.job_name,
        file_name=params.file_name,
    )
    return _serialize_response(response)
