"""Tool registry and orchestration."""

from __future__ import annotations

from collections.abc import Awaitable, Callable, Iterable
from typing import TYPE_CHECKING, Any

from ..exceptions import BunkerWebError, ToolExecutionError, ToolValidationError
from . import (
    ban_handlers,
    cache_handlers,
    config_handlers,
    core_handlers,
    instance_handlers,
    job_handlers,
    plugin_handlers,
    service_handlers,
)
from .params import (
    AuthParams,
    BanParams,
    BunkerWebClientProtocol,
    CacheDeleteBulkParams,
    CacheFetchParams,
    CacheFileKeyParams,
    CacheListParams,
    ConfigCreateParams,
    ConfigKeyParams,
    ConfigListParams,
    ConfigsDeleteParams,
    ConfigUpdateParams,
    ConfigUploadParams,
    ConfigUploadUpdateParams,
    DeleteServiceParams,
    EmptyParams,
    GetServiceParams,
    GlobalConfigReadParams,
    GlobalConfigUpdateParams,
    HostnameParams,
    InstanceCreateParams,
    InstancesDeleteParams,
    InstanceUpdateParams,
    JobsRunParams,
    ListServicesParams,
    PluginDeleteParams,
    PluginListParams,
    PluginUploadParams,
    ReloadParams,
    ServiceConvertParams,
    ServiceCreateParams,
    ServiceUpdateParams,
    SimpleHostnameParams,
    UnbanParams,
    _BaseToolParams,
)

if TYPE_CHECKING:
    from ..prompt_catalog import PromptCatalog


TOOL_DESCRIPTIONS: dict[str, str] = {
    "authenticate": "Authenticate against /auth to obtain a Biscuit token.",
    "ping": "Check if the BunkerWeb API is reachable.",
    "health": "Retrieve the lightweight health probe from the API.",
    "list_instances": "List registered BunkerWeb instances.",
    "instances_ping_all": "Ping all registered instances.",
    "instances_stop_all": "Stop all registered instances.",
    "instance_get": "Fetch details for a specific instance.",
    "instance_ping": "Ping a specific instance.",
    "instance_stop": "Stop a specific instance.",
    "instance_create": "Create a new instance.",
    "instance_update": "Update instance properties.",
    "instances_delete_bulk": "Delete multiple instances in a single call.",
    "instance_delete": "Delete a single instance.",
    "reload_instances": "Trigger configuration reload across all instances.",
    "reload_instance": "Trigger configuration reload on a single instance.",
    "list_bans": "List active bans across instances.",
    "ban_ip": "Ban one or multiple IP addresses.",
    "unban_ip": "Remove one or multiple bans.",
    "list_services": "List configured services.",
    "get_service": "Fetch configuration for a specific service.",
    "create_service": "Create a new service.",
    "update_service": "Update an existing service.",
    "delete_service": "Delete a service and its configuration.",
    "convert_service": "Convert a service between draft and online states.",
    "global_config_read": "Read the global configuration values.",
    "global_config_update": "Update global configuration values.",
    "configs_list": "List custom configuration snippets.",
    "config_get": "Fetch a specific configuration snippet.",
    "config_create": "Create a configuration snippet.",
    "config_update": "Update or rename a configuration snippet.",
    "config_delete": "Delete a specific configuration snippet.",
    "configs_delete_bulk": "Delete multiple configuration snippets.",
    "configs_upload": "Upload configuration snippets from file content.",
    "config_upload_update": "Update a configuration snippet using file upload.",
    "plugins_list": "List installed plugins.",
    "plugins_upload": "Upload and install plugins from archives.",
    "plugin_delete": "Delete an installed plugin.",
    "cache_list": "List cache files generated by jobs.",
    "cache_delete_bulk": "Delete multiple cache files.",
    "cache_fetch_file": "Fetch a cache file (base64-encoded when binary).",
    "cache_delete_file": "Delete a single cache file.",
    "jobs_list": "List scheduler jobs and history.",
    "jobs_run": "Trigger one or more scheduler jobs.",
}


class Tools:
    """Collection of callable tools wired to the BunkerWeb client."""

    def __init__(
        self, client: BunkerWebClientProtocol, prompt_catalog: PromptCatalog | None = None
    ) -> None:
        self._client = client
        from ..prompt_catalog import PromptCatalog

        self._prompt_catalog = prompt_catalog or PromptCatalog({})
        self._registry: dict[
            str, tuple[type[_BaseToolParams], Callable[[Any], Awaitable[dict[str, Any]]]]
        ] = {
            # Core handlers
            "authenticate": (AuthParams, self._wrap(core_handlers.handle_authenticate)),
            "ping": (EmptyParams, self._wrap(core_handlers.handle_ping)),
            "health": (EmptyParams, self._wrap(core_handlers.handle_health)),
            # Instance handlers
            "list_instances": (EmptyParams, self._wrap(instance_handlers.handle_list_instances)),
            "instances_ping_all": (
                EmptyParams,
                self._wrap(instance_handlers.handle_ping_instances),
            ),
            "instances_stop_all": (
                EmptyParams,
                self._wrap(instance_handlers.handle_stop_instances),
            ),
            "instance_get": (
                SimpleHostnameParams,
                self._wrap(instance_handlers.handle_get_instance),
            ),
            "instance_ping": (
                SimpleHostnameParams,
                self._wrap(instance_handlers.handle_ping_instance),
            ),
            "instance_stop": (
                SimpleHostnameParams,
                self._wrap(instance_handlers.handle_stop_instance),
            ),
            "instance_create": (
                InstanceCreateParams,
                self._wrap(instance_handlers.handle_create_instance),
            ),
            "instance_update": (
                InstanceUpdateParams,
                self._wrap(instance_handlers.handle_update_instance),
            ),
            "instances_delete_bulk": (
                InstancesDeleteParams,
                self._wrap(instance_handlers.handle_delete_instances),
            ),
            "instance_delete": (
                SimpleHostnameParams,
                self._wrap(instance_handlers.handle_delete_instance),
            ),
            "reload_instances": (
                ReloadParams,
                self._wrap(instance_handlers.handle_reload_instances),
            ),
            "reload_instance": (
                HostnameParams,
                self._wrap(instance_handlers.handle_reload_instance),
            ),
            # Ban handlers
            "list_bans": (EmptyParams, self._wrap(ban_handlers.handle_list_bans)),
            "ban_ip": (BanParams, self._wrap(ban_handlers.handle_ban_ip)),
            "unban_ip": (UnbanParams, self._wrap(ban_handlers.handle_unban_ip)),
            # Service handlers
            "list_services": (
                ListServicesParams,
                self._wrap(service_handlers.handle_list_services),
            ),
            "get_service": (GetServiceParams, self._wrap(service_handlers.handle_get_service)),
            "create_service": (
                ServiceCreateParams,
                self._wrap(service_handlers.handle_create_service),
            ),
            "update_service": (
                ServiceUpdateParams,
                self._wrap(service_handlers.handle_update_service),
            ),
            "delete_service": (
                DeleteServiceParams,
                self._wrap(service_handlers.handle_delete_service),
            ),
            "convert_service": (
                ServiceConvertParams,
                self._wrap(service_handlers.handle_convert_service),
            ),
            # Config handlers
            "global_config_read": (
                GlobalConfigReadParams,
                self._wrap(config_handlers.handle_read_global_config),
            ),
            "global_config_update": (
                GlobalConfigUpdateParams,
                self._wrap(config_handlers.handle_update_global_config),
            ),
            "configs_list": (ConfigListParams, self._wrap(config_handlers.handle_list_configs)),
            "config_get": (ConfigKeyParams, self._wrap(config_handlers.handle_get_config)),
            "config_create": (
                ConfigCreateParams,
                self._wrap(config_handlers.handle_create_config),
            ),
            "config_update": (
                ConfigUpdateParams,
                self._wrap(config_handlers.handle_update_config),
            ),
            "config_delete": (
                ConfigKeyParams,
                self._wrap(config_handlers.handle_delete_config),
            ),
            "configs_delete_bulk": (
                ConfigsDeleteParams,
                self._wrap(config_handlers.handle_delete_configs_bulk),
            ),
            "configs_upload": (
                ConfigUploadParams,
                self._wrap(config_handlers.handle_upload_configs),
            ),
            "config_upload_update": (
                ConfigUploadUpdateParams,
                self._wrap(config_handlers.handle_update_config_upload),
            ),
            # Plugin handlers
            "plugins_list": (PluginListParams, self._wrap(plugin_handlers.handle_list_plugins)),
            "plugins_upload": (
                PluginUploadParams,
                self._wrap(plugin_handlers.handle_upload_plugins),
            ),
            "plugin_delete": (
                PluginDeleteParams,
                self._wrap(plugin_handlers.handle_delete_plugin),
            ),
            # Cache handlers
            "cache_list": (CacheListParams, self._wrap(cache_handlers.handle_list_cache)),
            "cache_delete_bulk": (
                CacheDeleteBulkParams,
                self._wrap(cache_handlers.handle_delete_cache_bulk),
            ),
            "cache_fetch_file": (
                CacheFetchParams,
                self._wrap(cache_handlers.handle_fetch_cache_file),
            ),
            "cache_delete_file": (
                CacheFileKeyParams,
                self._wrap(cache_handlers.handle_delete_cache_file),
            ),
            # Job handlers
            "jobs_list": (EmptyParams, self._wrap(job_handlers.handle_list_jobs)),
            "jobs_run": (JobsRunParams, self._wrap(job_handlers.handle_run_jobs)),
        }

    def _wrap(
        self, handler: Callable[[BunkerWebClientProtocol, Any], Awaitable[dict[str, Any]]]
    ) -> Callable[[Any], Awaitable[dict[str, Any]]]:
        """Wrap a handler to inject the client."""

        async def wrapped(params: Any) -> dict[str, Any]:
            return await handler(self._client, params)

        return wrapped

    def list_descriptors(self) -> list[dict[str, Any]]:
        """Return JSON-serializable metadata describing available tools."""
        descriptors: list[dict[str, Any]] = []
        for name, (model, _) in self._registry.items():
            entry = {
                "name": name,
                "description": TOOL_DESCRIPTIONS[name],
                "input_schema": model.model_json_schema(),
            }
            prompt = self._prompt_catalog.get(name)
            if prompt:
                entry["prompt"] = prompt
            descriptors.append(entry)
        return descriptors

    def iter_registered(
        self,
    ) -> Iterable[
        tuple[
            str, type[_BaseToolParams], Callable[[Any], Awaitable[dict[str, Any]]], str, str | None
        ]
    ]:
        """Yield metadata for each registered tool."""
        for name, (model, handler) in self._registry.items():
            yield name, model, handler, TOOL_DESCRIPTIONS[name], self._prompt_catalog.get(name)

    def get_params_model(self, name: str) -> type[_BaseToolParams] | None:
        """Get the parameter model for a tool."""
        entry = self._registry.get(name)
        if entry is None:
            return None
        return entry[0]

    def get_tool(self, name: str) -> Callable[[dict[str, Any]], Awaitable[dict[str, Any]]] | None:
        """Get an executable tool by name."""
        entry = self._registry.get(name)
        if entry is None:
            return None
        params_model, handler = entry

        async def executor(payload: dict[str, Any]) -> dict[str, Any]:
            try:
                params = params_model.model_validate(payload)
            except Exception as exc:  # noqa: BLE001 - bubble up validation errors
                raise ToolValidationError(str(exc)) from exc
            try:
                return await handler(params)
            except BunkerWebError as exc:
                raise ToolExecutionError(str(exc)) from exc
            except Exception as exc:  # noqa: BLE001 - ensure consistent tool errors
                raise ToolExecutionError(str(exc)) from exc

        return executor

    def get_prompt(self, name: str) -> str | None:
        """Return the configured prompt for a tool, if any."""
        return self._prompt_catalog.get(name)
